name: test_localization
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  easy_localization: ^3.0.7
  easy_localization_loader: ^2.0.2
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  get: ^4.6.6
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
